---
- name: "Deploy Foreman Server"
  hosts: all
  remote_user: root
  gather_facts: yes
  vars_files:
    - vault.yml

  tasks:

    - include_vars:
        dir: extra_vars

    - name: Wait for server to come online
      wait_for_connection:
        delay: 60
        sleep: 10
        connect_timeout: 5
        timeout: 300

    - import_role:
        name: common

    - import_role:
        name: isc_dhcp_server
      when: foreman_proxy_dhcp

    - import_role:
        name: tftp
      when: foreman_proxy_tftp

    - import_role:
        name: nginx

    - import_role:
        name: awx

    - import_role:
        name: docker

    - import_role:
        name: awx
        tasks_from: container-tasks.yml

    - import_role:
        name: foreman

    - import_role:
        name: ansible-project
