---
- name: Install apt-cacher-ng
  package:
    name: apt-cacher-ng
    state: present

- name: Collect installed packages
  package_facts:

#- name: Collect apt-cacher-ng version
#  set_fact:
#    acng_pkg_version: "{{ ansible_facts.packages['apt-cacher-ng'][0]['version'] }}"
#
#- name: print acng version
#  debug:
#    msg: "{{ acng_pkg_version }}"
#  when: acng_pkg_version is version('1.0.0', '<')

- name: Template apt-cacher-ng config
  template:
    src: etc/apt-cacher-ng/acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
    mode: 644
    owner: root
    group: root
  notify: restart apt-cacher-ng

- name: Create CentOS mirrorlist map
  shell:
    cmd: curl https://www.centos.org/download/full-mirrorlist.csv | sed 's/^.*"http:/http:/' | sed 's/".*$//' | grep ^http >/etc/apt-cacher-ng/centos_mirrors
    creates: /etc/apt-cacher-ng/centos_mirrors
    executable: /bin/bash

- name: Enable/Start apt-cacher-ng service
  service:
    name: apt-cacher-ng
    state: started
    enabled: yes
