---
- name: Generate foreman database config from template
  template:
    src: etc/foreman/database.yml.j2
    dest: "{{ foreman_config_dir }}/database.yml"
    mode: 0755
    backup: yes
  notify: restart foreman
  register: db_config

- name: Generate foreman settings config from template
  template:
    src: etc/foreman/settings.yaml.j2
    dest: "{{ foreman_config_dir }}/settings.yaml"
    mode: 0755
    backup: yes
  notify: restart foreman
  register: settings_config

- name: Perform initial database setup (migrate)
  command: foreman-rake db:migrate
  register: migrate_results
  notify: restart foreman
  when: db_config is changed

- name: perform initial database setup (seed)
  command: foreman-rake db:seed
  register: seed_results
  notify: restart foreman
  when: settings_config is changed

- name: Check for foreman admin password change
  copy:
    dest: "{{ foreman_config_dir }}/password_configured"
    content: "{{ foreman_admin_password | checksum }}"
  register: foreman_pw_updated

- name: set foreman admin password
  command: "foreman-rake permissions:reset username=admin password={{ foreman_admin_password }}"
  when: foreman_pw_updated is changed
  no_log: True

- name: template foreman-proxy settings.yml
  template:
    src: etc/foreman-proxy/settings.yml.j2
    dest: "{{ foreman_proxy_config_dir }}/settings.yml"
    backup: yes
  notify:
    - restart foreman-proxy

- name: template foreman-proxy dhcp.yml
  template:
    src: etc/foreman-proxy/dhcp.yml.j2
    dest: "{{ foreman_proxy_config_dir }}/settings.d/dhcp.yml"
    backup: yes
  when: foreman_proxy_dhcp
  notify:
    - restart foreman-proxy

- name: template foreman-proxy dhcp_isc.yml
  template:
    src: etc/foreman-proxy/dhcp_isc.yml.j2
    dest: "{{ foreman_proxy_config_dir }}/settings.d/dhcp_isc.yml"
    backup: yes
  when: foreman_proxy_dhcp
  notify:
    - restart foreman-proxy

- name: fix dhcp config directory permissions
  file:
    path: "{{ foreman_proxy_dhcp_config_dir }}"
    mode: 0755
    state: directory
  when: foreman_proxy_dhcp
  notify:
    - restart foreman-proxy

- name: template foreman-proxy tftp.yaml
  template:
    src: etc/foreman-proxy/tftp.yml.j2
    dest: "{{ foreman_proxy_config_dir }}/settings.d/tftp.yml"
    backup: yes
  when: foreman_proxy_tftp
  notify:
    - restart foreman-proxy

- name: ensure correct permissions for tftp pxe directories
  file:
    path: "{{ foreman_proxy_tftp_dir }}/{{ item }}"
    owner: "{{ foreman_proxy_user }}"
    group: "{{ foreman_proxy_group }}"
    state: directory
  when: foreman_proxy_tftp
  with_items: "{{ foreman_proxy_tftp_pxe_dir }}"
