---
- name: domain
  foreman_domain:
    name: "home.prettybaked.com"
    description: "Example Domain"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://10.0.10.12"
    username: "foreman"
    password: "changeme123"
    state: present


- name: My subnet
  foreman_subnet:
    name: "10.0.10.0/24"
    network: "10.0.10.0"
    mask: "255.255.255.0"
    gateway: "10.0.10.1"
    from_ip: "10.0.10.240"
    to_ip: "10.0.10.250"
    boot_mode: "DHCP"
    dhcp_proxy: "foreman.home.prettybaked.com"
    tftp_proxy: "foreman.home.prettybaked.com"
    vlanid:
    mtu: 9000
    domains:
    - "example.org"
    organizations:
    - "Default Organization"
    locations:
    - "Default Location"
    server_url: "http://10.0.10.12"
    username: "foreman"
    password: "changeme123"
    state: present
