---
- name: domain
  foreman_domain:
    name: "{{ www_domain }}"
    description: "{{ www_domain }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present


- name: My subnet
  foreman_subnet:
    name: "10.0.10.0/24"
    network: "10.0.10.0"
    mask: "255.255.255.0"
    gateway: "10.0.10.1"
    from_ip: "10.0.10.240"
    to_ip: "10.0.10.250"
    boot_mode: "DHCP"
    dhcp_proxy: "smart-proxy"
    tftp_proxy: "smart-proxy"
    discovery_proxy: "smart-proxy"
    httpboot_proxy: "smart-proxy"
    vlanid:
    mtu: 9000
    domains:
    - "{{ www_domain }}"
    organizations:
    - "Default Organization"
    locations:
    - "Default Location"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present

- foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "default_pxe_item_global"
    value: "discovery"

- foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "update_ip_from_built_request"
    value: "Yes"
- foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "token_duration"
    value: "0"
- foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "discovery_auto"
    value: "Yes"
- foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "discovery_location"
    value: "Default Location"
- foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "discovery_organization"
    value: "Default Organization"