---
- name: "Default Organization"
  theforeman.foreman.foreman_organization:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "Default Organization"
    state: present

- name: "Default Location"
  theforeman.foreman.foreman_location:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "Default Location"
    organizations:
      - "Default Organization"
    state: present

- name: Update Foreman Settings
  theforeman.foreman.foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ foreman_default_settings }}"

- name: Configure Additional Foreman Settings
  theforeman.foreman.foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ foreman_extra_settings }}"

- name: "Update global parameters"
  theforeman.foreman.foreman_global_parameter:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    parameter-type: "{{ item.parameter_type }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present_with_defaults
  loop: "{{ foreman_global_parameters }}"
