---
- name: "Create OS Install Mediums"
  theforeman.foreman.foreman_installation_medium:
    name: "{{ item.name }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    os_family: "{{ item.os_family }}"
    path: "{{ item.path }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ foreman_installation_mediums }}"
  loop_control:
    label: "{{ item.name }}: {{ item.path }} "
  when:
    - foreman_installation_mediums is defined
    - foreman_installation_mediums != None

- name: "Create Operating Systems"
  theforeman.foreman.foreman_operatingsystem:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    release_name: "{{ item.release_name | default(omit) }}"
    family: "{{ item.family }}"
    major: "{{ item.major }}"
    minor: "{{ item.minor }}"
    provisioning_templates: "{{ item.provisioning_templates | default(omit) }}"
    ptables: "{{ item.ptables | default(omit) }}"
    architectures: "{{ item.architectures }}"
    media: "{{ item.media }}"
    password_hash: "{{ item.password_hash | default('SHA256') }}"
    parameters: "{{ item.parameters | default(omit) }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ foreman_operatingsystems }}"
  loop_control:
    label: "{{ item.name }} {{ item.major }}.{{ item.minor }}"
  when:
    - foreman_operatingsystems is defined
    - foreman_operatingsystems != None

- name: "Create Template Associations"
  theforeman.foreman.foreman_os_default_template:
    operatingsystem: "{{ item.operatingsystem }}"
    template_kind: "{{ item.template_kind }}"
    provisioning_template: "{{ item.provisioning_template }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ foreman_os_default_templates }}"
  loop_control:
    label: "{{ item.operatingsystem }} {{ item.template_kind }}: {{ item.provisioning_template }}"
  when:
    - foreman_os_default_templates is defined
    - foreman_os_default_templates != None
