---
- name: Create compute resources
  theforeman.foreman.foreman_compute_resource:
    name: "{{ item.name }}"
    provider: "{{ item.provider }}"
    provider_params: "{{ item.provider_params }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ foreman_compute_resources }}"
  when:
    - foreman_compute_resources is defined
    - foreman_compute_resources != None

- name: "Enable/Disable VM console passwords for Libvirt providers"
  command: >
    hammer -r compute-resource update --name {{ item.name }}
     --set-console-password {% if foreman_libvirt_set_console_password %}'1'{% else %}'0'{% endif %}
  loop: "{{ foreman_compute_resources }}"
  when:
    - foreman_compute_resources is defined
    - foreman_compute_resources != None
    - item.provider == "libvirt"
  changed_when: False

- name: "Create Hostgroups"
  theforeman.foreman.foreman_hostgroup:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    architecture: "{{ item.architecture | default(omit) }}"
    operatingsystem: "{{ item.operatingsystem | default(omit) }}"
    medium: "{{ item.medium | default(omit) }}"
    ptable: "{{ item.ptable | default(omit) }}"
    pxe_loader: "{{ item.pxe_loader | default(omit) }}"
    domain: "{{ item.domain | default(omit) }}"
    subnet: "{{ item.subnet | default(omit) }}"
    locations:
      - "Default Location"
    organization: "Default Organization"
    parent: "{{ item.parent | default(omit) }}"
    compute_resource: "{{ item.compute_resource | default(omit) }}"
    #pxe_loader: "{{ item.pxe_loader }}"
    parameters: "{{ item.parameters | default(omit) }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ foreman_hostgroups }}"
  when:
    - foreman_hostgroups is defined
    - foreman_hostgroups != None



#- name: "Auto-create hostgroups for compute resources"
#  theforeman.foreman.foreman_hostgroup:
#    name: "{{ item.name }}"
#    description: "{{ item.name }} resource group"
#    compute_resource: "{{ item.name }}"
#    parent: "{{ item.parent | default('kvm') }}"
#    locations:
#      - "Default Location"
#    organization: "Default Organization"
#    server_url: "http://{{ foreman_proxy_bind_host }}"
#    username: "{{ foreman_admin_user }}"
#    password: "{{ foreman_admin_password }}"
#    state: present
#  loop: "{{ foreman_compute_resources }}"
#  when:
#    - foreman_compute_resources is defined
#    - foreman_compute_resources != None
