---
- name: "Create Domain"
  theforeman.foreman.foreman_domain:
    name: "{{ www_domain }}"
    description: "{{ www_domain }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present

- name: Create Subnets
  theforeman.foreman.foreman_subnet:
    name: "{{ item.name }}"
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
    gateway: "{{ item.gateway }}"
    from_ip: "{{ item.from_ip }}"
    to_ip: "{{ item.to_ip }}"
    dns_primary: "{{ item.dns_primary | default(omit) }}"
    dns_secondary: "{{ item.dns_secondary | default(omit) }}"
    boot_mode: "{{ item.boot_mode | default('DHCP') }}"
    dhcp_proxy: "{{ item.dhcp_proxy | default(omit) }}"
    tftp_proxy: "{{ item.tftp_proxy | default(omit) }}"
    discovery_proxy: "{{ item.discovery_proxy | default(omit) }}"
    httpboot_proxy: "{{ item.httpboot_proxy | default(omit) }}"
    vlanid: "{{ item.vlanid | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    domains: "{{ item.domains | default(www_domain) }}"
    organizations:
    - "Default Organization"
    locations:
    - "Default Location"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_proxy_dhcp_subnets }}"
  when:
    - foreman_proxy_dhcp_subnets is defined
    - foreman_proxy_dhcp_subnets != None
