---
- name: "Create Domains"
  theforeman.foreman.foreman_domain:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    parameters: "{{ item.parameters | default(omit) }}"
    dns_proxy: "{% if foreman_proxy_dns %}{{ item.dns_proxy | default(omit) }}{% else %}{{ omit }}{% endif %}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_domains }}"
  when:
    - foreman_domains is defined
    - foreman_domains != None

- name: Create Subnets
  theforeman.foreman.foreman_subnet:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    network: "{{ item.network }}"
    mask: "{{ item.mask | default(omit) }}"
    cidr: "{{ item.cidr | default(omit) }}"
    gateway: "{{ item.gateway }}"
    from_ip: "{{ item.from_ip }}"
    to_ip: "{{ item.to_ip }}"
    dns_primary: "{{ item.dns_primary | default(omit) }}"
    dns_secondary: "{{ item.dns_secondary | default(omit) }}"
    boot_mode: "{{ item.boot_mode | default('Static') }}"
    dhcp_proxy: "{% if foreman_proxy_dhcp %}{{ item.dhcp_proxy | default(omit) }}{% else %}{{ omit }}{% endif %}"
    tftp_proxy: "{% if foreman_proxy_tftp %}{{ item.tftp_proxy | default(omit) }}{% else %}{{ omit }}{% endif %}"
    dns_proxy: "{% if foreman_proxy_dns %}{{ item.dns_proxy | default(omit) }}{% else %}{{ omit }}{% endif %}"
    discovery_proxy: "{% if foreman_proxy_tftp %}{{ item.discovery_proxy | default(omit) }}{% else %}{{ omit }}{% endif %}"
    httpboot_proxy: "{% if foreman_proxy_tftp %}{{ item.httpboot_proxy | default(omit) }}{% else %}{{ omit }}{% endif %}"
    remote_execution_proxies: "{% if foreman_proxy_remote_execution %}{{ item.remote_execution_proxies | default(omit) }}{% else %}{{ omit }}{% endif %}"
    vlanid: "{{ item.vlanid | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    domains: "{{ item.domains | default(www_domain) }}"
    parameters: "{{ item.parameters | default(omit) }}"
    organizations:
    - "Default Organization"
    locations:
    - "Default Location"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_proxy_dhcp_subnets }}"
  when:
    - foreman_proxy_dhcp_subnets is defined
    - foreman_proxy_dhcp_subnets != None
  register: foreman_network_results
  changed_when: foreman_network_results.diff.before != foreman_network_results.diff.after
