---
- name: "Update provisioning templates"
  theforeman.foreman.foreman_provisioning_template:
    template: '{{ lookup("file", item.src) }}'
    locked: no
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  with_filetree: 'files/provisioning'
  when:
    - foreman_proxy_tftp
    - item.state == 'file'
  notify: rebuild pxe default configs

- meta: flush_handlers

- name: Rebuild Foreman default PXE configurations
  command: hammer template build-pxe-default
  when:
    - foreman_proxy_tftp
    - foreman_pxe_templates_updated | default(false)

#- name: "Lock provisioning templates"
#  theforeman.foreman.foreman_provisioning_template:
#    template: '{{ lookup("file", item.src) }}'
#    locked: yes
#    locations:
#      - "Default Location"
#    organizations:
#      - "Default Organization"
#    server_url: "http://{{ foreman_proxy_bind_host }}"
#    username: "{{ foreman_admin_user }}"
#    password: "{{ foreman_admin_password }}"
#    state: present
#  with_filetree: 'files/provisioning'
#  when: item.state == 'file'
#  notify: rebuild pxe default configs
