---
- name: "Update provisioning templates"
  theforeman.foreman.foreman_provisioning_template:
    template: "{{ lookup('file', item.src) }}"
    locked: no
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}:{{ foreman_port }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ lookup('filetree', 'files/provisioning/', wantlist=True) }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - foreman_proxy_tftp
    - item.state == 'file'
  notify: rebuild pxe default configs

- meta: flush_handlers

- name: Rebuild Foreman default PXE configurations
  command: hammer template build-pxe-default
  when:
    - foreman_proxy_tftp
    - foreman_pxe_templates_updated | default(false)
