---
- name: Create hosts via hammer cli
  command: >
    hammer -r host create --name {{ item.value.name }} --hostgroup {{ item.value.hostgroup }} --location 'Default Location' --organization 'Default Organization'  
    --interface '{
    {% if item.value.provider is defined and item.value.provider == "kvm" %}
    "compute_bridge": "br{{ item.value.vlan_id | regex_replace('10', '0') | ddefault('0') }}", 
    "compute_model": "virtio", 
    "compute_type": "bridge", 
    {% endif %}
    {% if item.value.ip is defined %}
    "ip": "{{ item.value.ip }}", 
    {% endif %}
    "identifier": "eth0" 
    }'
    {% if item.value.provider is defined and item.value.provider == "kvm" %}
    --compute-attributes '{
    "cpus": {{ item.value.cpu_cores }}, 
    "memory": {{ item.value.memory | human_to_bytes }}, 
    "start": 1
    }'
    {% endif %}
    {% if item.value.provider is defined and item.value.provider == "kvm" %}
    --volume '{
    "capacity": "{{ item.value.disk_size | human_to_bytes // 1073741824 }}G", 
    "format_type": "qcow2"
    }'
    {% endif %}
  loop: "{{ foreman_hosts | dict2items }}"
  register: foreman_hosts_created
  failed_when:
    - foreman_hosts_created.rc != 65
    - foreman_hosts_created.rc != 0
