---
- name: Update Foreman Settings
  block:
    - name: Combine Foreman default settings with user-defined settings
      set_fact:
        foreman_settings: '{{ foreman_default_settings + foreman_extra_settings }}'
    - name: Update Foreman Settings
      theforeman.foreman.foreman_setting:
        server_url: "http://{{ foreman_proxy_bind_host }}"
        username: "{{ foreman_admin_user }}"
        password: "{{ foreman_admin_password }}"
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop: "{{ foreman_settings }}"

- name: "Update global parameters"
  theforeman.foreman.foreman_global_parameter:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    parameter_type: "{{ item.parameter_type | default('string') }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present_with_defaults
  loop: "{{ foreman_global_parameters }}"
  when:
    - foreman_global_parameters is defined
    - foreman_global_parameters != None
