---
- name: "Default Organization"
  theforeman.foreman.foreman_organization:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "Default Organization"
    state: present

- name: "Default Location"
  theforeman.foreman.foreman_location:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "Default Location"
    organizations:
      - "Default Organization"
    state: present

- name: "Create Domain"
  theforeman.foreman.foreman_domain:
    name: "{{ www_domain }}"
    description: "{{ www_domain }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present

- name: Create Subnets
  theforeman.foreman.foreman_subnet:
    name: "{{ item.name }}"
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
    gateway: "{{ item.gateway }}"
    from_ip: "{{ item.from_ip }}"
    to_ip: "{{ item.to_ip }}"
    dns_primary: "{{ item.dns_primary | default(omit) }}"
    dns_secondary: "{{ item.dns_secondary | default(omit) }}"
    boot_mode: "DHCP"
    dhcp_proxy: "smart-proxy"
    tftp_proxy: "smart-proxy"
    discovery_proxy: "smart-proxy"
    httpboot_proxy: "smart-proxy"
    vlanid: "{{ item.vlanid | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    domains: "{{ item.domains | default(www_domain) }}"
    organizations:
    - "Default Organization"
    locations:
    - "Default Location"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_proxy_dhcp_subnets }}"


- name: Update Foreman Settings
  theforeman.foreman.foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ foreman_default_settings }}"

- name: Configure Additional Foreman Settings
  theforeman.foreman.foreman_setting:
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ foreman_extra_settings }}"

- name: "Create OS Install Mediums"
  theforeman.foreman.foreman_installation_medium:
    name: "{{ item.name }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    os_family: "{{ item.os_family }}"
    path: "{{ item.path }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_installation_mediums }}"


- name: "Create Operating Systems"
  theforeman.foreman.foreman_operatingsystem:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    release_name: "{{ item.release_name }}"
    family: "{{ item.family }}"
    major: "{{ item.major }}"
    minor: "{{ item.minor }}"
    provisioning_templates: "{{ item.provisioning_templates | default(omit) }}"
    ptables: "{{ item.ptables | default(omit) }}"
    architectures: "{{ item.architectures }}"
    media: "{{ item.media }}"
    password_hash: "{{ item.password_hash | default('SHA256') }}"
    parameters: "{{ item.parameters | default(omit) }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_operatingsystems }}"

- name: "Create Template Associations"
  theforeman.foreman.foreman_os_default_template:
    operatingsystem: "{{ item.operatingsystem }}"
    template_kind: "{{ item.template_kind }}"
    provisioning_template: "{{ item.provisioning_template }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_os_default_templates }}"

- name: "Create Hostgroups"
  theforeman.foreman.foreman_hostgroup:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    architecture: "{{ item.architecture }}"
    operatingsystem: "{{ item.operatingsystem }}"
    medium: "{{ item.medium }}"
    ptable: "{{ item.ptable }}"
    domain: "{{ item.domain }}"
    subnet: "{{ item.subnet }}"
    locations:
      - "Default Location"
    organization: "Default Organization"
    #pxe_loader: "{{ item.pxe_loader }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_hostgroups }}"

- name: "Update global parameters"
  theforeman.foreman.foreman_global_parameter:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present_with_defaults
  loop: "{{ foreman_global_parameters }}"

- name: "Update provisioning templates"
  theforeman.foreman.foreman_provisioning_template:
    template: '{{ lookup("file", item.src) }}'
    locked: no
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  with_filetree: 'files/provisioning'
  when: item.state == 'file'
  notify: rebuild pxe default configs

- name: "Lock provisioning templates"
  theforeman.foreman.foreman_provisioning_template:
    template: '{{ lookup("file", item.src) }}'
    locked: yes
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  with_filetree: 'files/provisioning'
  when: item.state == 'file'
  notify: rebuild pxe default configs

- name: Create compute resources
  foreman_compute_resource:
    name: "{{ item.name }}"
    provider: "{{ item.provider }}"
    provider_params: "{{ item.provider_params }}"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    server_url: "http://{{ foreman_proxy_bind_host }}"
    username: "{{ foreman_admin_user }}"
    password: "{{ foreman_admin_password }}"
    state: present
  loop: "{{ foreman_compute_resources }}"
