---
- name: Query foreman hosts
  command: hammer -r host list
  register: hostlist

- debug:
    msg: "{{ hostlist }}"
  tags:
    - never
    - debug

- name: Get host build status
  shell: |
    hammer -r host info --name {{ item.name }}.{{ www_domain }} | egrep -i '(build status)' | sed -r 's/^.*:\s+(\w.*)$/\1/'
  register: buildstatus
  loop: "{{ foreman_hosts }}"
  when: item.name in hostlist.stdout

- debug:
    msg: "{{ item }}"
  loop: "{{ buildstatus.results }}"
  when: item.changed
  tags:
    - never
    - debug

- name: "Create hosts via hammer cli"
  command: >
    {% if item.item.name not in hostlist.stdout %}
    {% set interface_cmd = '{}' %}
    hammer -r host create --name '{{ item.item.name }}' --hostgroup '{{ item.item.hostgroup }}' --build '1'
    --location 'Default Location' --organization 'Default Organization'
    {% if item.item.operatingsystem is defined %}
    --operatingsystem '{{ item.item.operatingsystem }}'
    --media '{% for os in foreman_operatingsystems %}{% if os.description == {{ item.item.operatingsystem }} %}{{ query('items', os.media) }}{% endif %}{% endfor %}'
    --partition-table '{% for os in foreman_operatingsystems %}{% if os.description == {{ item.item.operatingsystem }} %}{{ query('items', os.ptables[0]) }}{% endif %}{% endfor %}'
    {% endif %}
    {% if item.item.subnet is defined %}
    --subnet '{{ item.item.subnet }}'
    {% endif %}
    {% if item.item.provider is defined and item.item.provider == "kvm" %}
    --compute-resource '{{ item.item.compute_resource }}'
    --compute-attributes '{
    "cpus": {{ item.item.cpu_cores }},
    "memory": {{ item.item.memory | regex_replace("^([0-9]+)\s+?.*$", "\1GB") | human_to_bytes }},
    "start": "0"
    }'
    --volume '{
    "capacity": {{ (item.item.disk_size | regex_replace("^([0-9]+)\s+?.*$", "\1GB") | human_to_bytes // 1073741824) }},
    "format_type": "qcow2"
    }'
    {% set interface_cmd = interface_cmd | from_json | combine({ 'compute_bridge': 'br' + ( item.item.vlan_id | default("0") | regex_replace("10", "0") ) },
      { 'compute_model': 'virtio' },
      { 'compute_type': 'bridge' }) | to_json %}
    {% endif %}
    {% if item.item.ip is defined %}
    {% set interface_cmd = interface_cmd | from_json | combine({ 'ip': item.item.ip }) | to_json %}
    {% endif %}
    {% if item.item.interface is defined %}
    {% set interface_cmd = interface_cmd | from_json | combine({ 'identifier': item.item.interface }) | to_json %}
    {% endif %}
    {% if item.item.mac_address is defined %}
    {% set interface_cmd = interface_cmd | from_json | combine({ 'mac': item.item.mac_address }) | to_json %}
    {% endif %}
    --interface {{ interface_cmd | to_json }}
    {% if item.item.provider is defined and item.item.provider == "ipmi" %}
    --interface '{
    "ip": "{{ item.item.ipmi_ip }}",
    "mac": "{{ item.item.ipmi_mac_address }}",
    "type": "bmc",
    "provider": "ipmi",
    "username": "{{ item.item.ipmi_username }}",
    "password": "{{ item.item.ipmi_password }}"
    }'
    {% endif %}
    {% else %}
    {% if "Pending" not in item.stdout %}
    hammer -r host update --name {{ item.item.name }}.{{ www_domain }} --build '1'
    {% else %}
    hammer -qr host info --name {{ item.item.name }}.{{ www_domain }}
    {% endif %}
    {% endif %}
  loop: "{{ buildstatus.results }}"
  register: foreman_hosts_created
  changed_when: foreman_hosts_created.stdout == "Host updated." or foreman_hosts_created.stdout == "Host created."

- debug:
    msg: "{{ item }}"
  loop: "{{ foreman_hosts_created.results  }}"
  tags:
    - never
    - debug

- name: Get host power status
  shell: |
    hammer -r host status --name {{ item.item.item.name }}.{{ www_domain }} | grep -i power | awk '{print $2}'
  register: powerstatus
  loop: "{{ foreman_hosts_created.results  }}"
  when: item.changed

- debug:
    msg: "{{ item }}"
  loop: "{{ powerstatus.results }}"
  tags:
    - never
    - debug

#- name: Set host to boot from network device
#  command: >
#    hammer -r host boot --device pxe --name {{ item.item.item.name }}.{{ www_domain }}
#  loop:
#    "{{ foreman_hosts_created.results }}"
#  when:
#    - item.changed
#    - item.item.item.provider == "ipmi"

- name: Set Boot Device to PXE (ipmi)
  command: >
    ipmitool -I lanplus
     -U {{ item.item.item.item.ipmi_username }}
     -P {{ item.item.item.item.ipmi_password }}
     -H {{ item.item.item.item.ipmi_ip }}
     chassis bootdev pxe options=persistent,verbose=yes,cons_redirect=enable
  loop: "{{ powerstatus.results }}"
  when:
    - item.changed
    - item.item.item.item.provider == "ipmi"

- name: Host Power-Cycle
  command: >
    hammer -r host
    {% if item.stdout == "off" %}
    start
    {% else %}
    reset
    {% endif %}
    --name {{ item.item.item.item.name }}.{{ www_domain }}
  loop: "{{ powerstatus.results }}"
  when:
    - item.changed
    #- item.item.item.item.provider != "ssh
