---

#- name: Create hosts via hammer cli
#  #command: hammer -r host create --name {{ item.name }} --hostgroup {{ item.hostgroup }} --location 'Default Location' --organization 'Default Organization' --managed 0 --build 0
#  command: >
#    hammer -r host create --name {{ item.name }} --hostgroup {{ item.hostgroup }} --location 'Default Location' --organization 'Default Organization' 
#    {% if item.kvm is defined and item.kvm %}
#    --interface compute_type=bridge,compute_bridge=br{{ item.vlan | default('0') }},compute_model=virtio,identifier=eth0,name=eth0 
#    --compute-attributes cpus={{ item.cpu_count }},memory={{ item.memory_gb }}192000000,start=1 
#    --volume capacity={{ item.disk_gb }}G,format_type=qcow2
#    {% else %}
#    --interface identifier=eth0,name=eth0
#    {% endif %}
#  loop: "{{ foreman_hosts }}"
#  register: foreman_hosts_created
#  failed_when:
#    - foreman_hosts_created.rc != 65
#    - foreman_hosts_created.rc != 0
#  tags:
#    - hostcreate

- name: Create hosts via hammer cli
  command: >
    hammer -r host create --name {{ host.name }} --hostgroup {{ host.hostgroup }} --location 'Default Location' --organization 'Default Organization' 
    --interface={{ host.interface_attributes }} 
    {% if host.compute_attributes is defined %}
    --compute-attributes={{ host.compute_attributes }} 
    {% endif %}
    {% if host.volume_attributes is defined %}
    --volume={{ host.volume_attributes }}
    {% endif %}
  register: foreman_hosts_created
  failed_when:
    - foreman_hosts_created.rc != 65
    - foreman_hosts_created.rc != 0
  tags:
    - hostcreate


#- name: Enable Host Builds via hammer cli
#  command: hammer -r host update --name {{ item.name }}.{{ www_domain }} --managed 1 --build 1
#  loop: "{{ foreman_hosts }}"
#  tags:
#    - hostcreate
#
#- name: Boot host via hammer cli
#  command: hammer -r host start --name {{ item.name }}.{{ www_domain }}
#  loop: "{{ foreman_hosts }}"
#  tags:
#    - hostcreate