---

- name: Create hosts via hammer cli
  command: hammer -r host create --name {{ item.name }} --mac {{ item.mac_address }} --hostgroup {{ item.hostgroup }} --location 'Default Location' --organization 'Default Organization' --managed 0 --build 0
  loop: "{{ foreman_hosts }}"
  register: foreman_hosts_created
  failed_when:
    - foreman_hosts_created.rc != 65
    - foreman_hosts_created.rc != 0
  tags:
    - hostcreate

- name: Enable Host Builds via hammer cli
  command: hammer -r host update --name {{ item.name }}.{{ item.domain }} --managed 1 --build 1
  loop: "{{ foreman_hosts }}"
  tags:
    - hostcreate

#  command: hammer host create --name {{ item.name }} --mac {{ item.mac_address }} mac={{ item.mac_address }},type=interface,primary=true,provision=true,managed=true --hostgroup {{ item.hostgroup }}

#- name: Build Hosts via REST API
#  uri:
#    url: "http://{{ foreman_proxy_bind_host }}/api/hosts"
#    method: POST
#    user: "{{ foreman_admin_user }}"
#    password: "{{ foreman_admin_password }}"
#    force_basic_auth: yes
#    body_format: json
#    body:
#      {
#        "host": {
#          "name": "{{ item.name }}",
#          "mac": "{{ item.mac_address }}",
#          "hostgroup_id": 1,
#          "build": true,
#          "enabled": true,
#          "managed": true
#          }
#        }
#    status_code: 201
#    return_content: yes
#  loop: "{{ foreman_hosts }}"
#  tags:
#    - hostcreate


#- name: "Create Host Entries via foreman-ansible modules"
#  foreman_host:
#    name: "{{ item.name }}.{{ item.domain }}"
#    build: "{{ item.build | default('true') }}"
#    enabled: "{{ item.enabled | default('true') }}"
#    hostgroup: "{{ item.hostgroup }}"
#    location: "Default Location"
#    organization: "Default Organization"
#    server_url: "http://{{ foreman_proxy_bind_host }}"
#    interfaces:
#      mac: "{{ item.mac_address }}"
#    username: "{{ foreman_admin_user }}"
#    password: "{{ foreman_admin_password }}"
#    state: present
#  loop: "{{ foreman_hosts }}"
#  tags:
#    - hostcreate

- name: Get list of all hosts via hammer cli
  command: hammer -r --no-headers host list --fields id
  register: foreman_hosts_created
  tags:
    - hostcleanup

- name: Delete hosts via hammer cli
  command: hammer -r host delete --id {{ item }}
  loop: "{{ foreman_hosts_created.stdout_lines | list }}"
  tags:
    - hostcleanup