---

- name: "Disable SELinux, Configure FirewallD to ACCEPT from all [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Get FirewallD public zone target
      command: firewall-cmd --zone public --get-target --permanent
      register: firewalld_public_target
      changed_when: False
    - name: Set FirewallD public zone to allow-all
      command: firewall-cmd --permanent --set-target=ACCEPT
      when:
        - firewalld_public_target.stdout != "ACCEPT"
  when: ansible_os_family == "RedHat"

- name: Install any necessary dependencies [CentOS]
  yum:
    name: "{{ foreman_dependency_pkgs }}"
    state: present
    update_cache: yes

- name: Add EPEL repository [CentOS]
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Add Foreman repositories [CentOS]
  yum:
    name: "{{ foreman_yum_repo_url }}/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/foreman-release.rpm"
    state: present
    update_cache: yes

- name: Install Foreman SCL repository
  yum:
    name: foreman-release-scl
    state: present
    update_cache: yes

- name: Install foreman packages [CentOS]
  yum:
    name: "{{ foreman_pkgs }}"
    state: latest
    update_cache: yes
  register: foreman_installed
  notify: capture_foreman_version

- name: Install foreman proxy packages [Centos]
  yum:
    name: "{{ foreman_proxy_pkgs }}"
    state: latest
    update_cache: yes

- name: Install foreman python2 requirements
  pip:
    name: "{{ foreman_python2_pkgs }}"
    state: present
    executable: pip2
  when:
    - ansible_python.version.major == 2

- name: Install foreman python3 requirements
  pip:
    name: "{{ foreman_python3_pkgs }}"
    state: present
    executable: pip3
  when:
    - ansible_python.version.major == 3

- name: template /etc/default/foreman
  template:
    src: etc/default/foreman.j2
    dest: "/etc/default/foreman"
    backup: no
  notify: restart foreman

- name: Enable the foreman service
  systemd:
    name: foreman
    enabled: yes
  when: foreman_enable_service
