---

- name: "Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Configure Firewalld allowed ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ foreman_allowed_ports }}"
  when: ansible_os_family == "RedHat"

- name: Install any necessary dependencies [CentOS]
  yum:
    name: "{{ foreman_dependency_pkgs }}"
    state: present
    update_cache: yes

- name: Add EPEL repository [CentOS]
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Add Foreman repositories [CentOS]
  yum:
    name: "{{ foreman_yum_repo_url }}/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/foreman-release.rpm"
    state: present
    update_cache: yes

- name: Install Foreman SCL repository
  yum:
    name: foreman-release-scl
    state: present
    update_cache: yes

- name: Install foreman packages [CentOS]
  yum:
    name: "{{ foreman_pkgs }}"
    state: present
    update_cache: yes
  notify: foreman_installed

- name: Install foreman proxy packages [Centos]
  yum:
    name: "{{ foreman_proxy_pkgs }}"
    state: present
    update_cache: yes
  notify: foreman_proxy_installed

- name: Install foreman python2 requirements
  pip:
    name: "{{ foreman_python2_pkgs }}"
    state: present
    executable: pip2
  when:
    - ansible_python.version.major == 2

- name: Install foreman python3 requirements
  pip:
    name: "{{ foreman_python3_pkgs }}"
    state: present
    executable: pip3
  when:
    - ansible_python.version.major == 3

#- name: Workaround for Foreman Smart-Proxy Ansible Plugin under Python2
#  block:
#
#    - name: Gather the rpm package facts
#      package_facts:
#        manager: auto
#
#    - name: Download rubygem-smart_proxy_ansible package
#      yum:
#        name: "{{ foreman_smart_proxy_ansible_pkg }}"
#        download_only: yes
#        download_dir: /tmp
#      when: foreman_smart_proxy_ansible_pkg not in hostvars[inventory_hostname].packages
#
#    - name: Install rubygem-smart_proxy_ansible
#      command:
#        cmd: "rpm -ivh --nodeps /tmp/{{ foreman_smart_proxy_ansible_pkg }}*.rpm"
#        warn: false
#      when: foreman_smart_proxy_ansible_pkg not in hostvars[inventory_hostname].packages
#
#  when:
#    - ansible_python.version.major == 2
#
#- name: Install Foreman Smart-Proxy Ansible Plugin under Python3
#  yum:
#    name: "{{ foreman_smart_proxy_ansible_pkg }}"
#    state: present
#    update_cache: yes
#  when:
#    - ansible_python.version.major == 3

- name: template /etc/default/foreman
  template:
    src: etc/default/foreman.j2
    dest: "/etc/default/foreman"
    backup: no
  notify: restart foreman

- name: Enable the foreman service
  systemd:
    name: foreman
    state: started
    enabled: yes
    daemon_reload: yes
  when: foreman_enable_service
