- include_tasks: install-debian.yml
  when: ansible_os_family == "Debian"

#- include_tasks: install-redhat.yml
#  when: ansible_os_family == "RedHat"

- name: Start the foreman service
  systemd:
    name: foreman
    state: started
    enabled: yes

- name: Start the foreman-proxy service
  systemd:
    name: foreman-proxy
    state: restarted
    enabled: yes

- name: Capture foreman version information
  command: foreman version
  register: foreman_capture_version

- name: Capture foreman version, branch, and commit
  set_fact:
    foreman_version: "{{ foreman_capture_version.stdout }}"

- debug:
    msg: "Foreman Installed Version is: {{ foreman_version }}"
