- include_tasks: install-debian.yml
  when: ansible_os_family == "Debian"

#- include_tasks: install-redhat.yml
#  when: ansible_os_family == "RedHat"

- name: Start the foreman service
  systemd:
    name: foreman
    state: started
    enabled: yes

- name: Start the foreman-proxy service
  systemd:
    name: foreman-proxy
    state: started
    enabled: yes