- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- import_tasks: install.yml
  tags: [foreman, foremaninstall ]

- import_tasks: configure.yml
  tags: [foreman, foremanconfigure ]

- name: Start the foreman service
  systemd:
    name: foreman
    state: restarted
    enabled: yes
  register: foreman_started
  when: foreman_enable_service
  tags: [foreman, foremanconfigure, foremanservice]
  notify:
    - restart nginx

- name: Verify foreman HTTP service is listening
  wait_for:
    host: "{{ foreman_interface | default(\"localhost\", true) }}"
    port: "{{ foreman_port | default('3000') }}"
    delay: 5
  when: foreman_started.changed and foreman_enable_service
  ignore_errors: yes
  register: foreman_start_attempt
  tags: [foreman, foremanconfigure, foremanservice]

- name: Get foreman journald logs if service does not appear to be up
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value foreman.service`
  register: foreman_journal
  when: foreman_start_attempt.failed is defined and foreman_start_attempt.failed == True
  tags: [foreman, foremanconfigure, foremanservice]

- fail:
    msg: "{{ foreman_journal.stdout_lines }}"
  when: foreman_start_attempt.failed is defined and foreman_start_attempt.failed == True
  tags: [foreman, foremanconfigure, foremanservice]

- name: Start the foreman-proxy service
  systemd:
    name: foreman-proxy
    state: restarted
    enabled: yes
  register: foreman_proxy_started
  when: foreman_proxy_enable_service
  tags: [foreman, foremanconfigure, foremanproxyservice ]

- name: Verify foreman-proxy service is listening
  wait_for:
    host: "{{ foreman_proxy_bind_host | default(ansible_default_ipv4.address) }}"
    port: "{{ foreman_proxy_port }}"
    delay: 5
  when: foreman_proxy_started.changed and foreman_proxy_enable_service
  ignore_errors: yes
  register: foreman_proxy_start_attempt
  tags: [foreman, foremanconfigure, foremanproxyservice ]

- name: Get foreman-proxy journald logs if service does not appear to be up
  shell: journalctl _SYSTEMD_INVOCATION_ID=`systemctl show -p InvocationID --value foreman-proxy.service`
  register: foreman_proxy_journal
  when: foreman_proxy_start_attempt.failed is defined and foreman_proxy_start_attempt.failed == True
  tags: [foreman, foremanconfigure, foremanproxyservice ]

- fail:
    msg: "{{ foreman_proxy_journal.stdout_lines }}"
  when: foreman_proxy_start_attempt.failed is defined and foreman_proxy_start_attempt.failed == True
  tags: [foreman, foremanconfigure, foremanproxyservice ]

- meta: flush_handlers

- import_tasks: smart-proxy.yml
  tags: [foreman, foremancustomize, foremansmartproxy]

- import_tasks: foreman-custom-config.yml
  tags: [foreman, foremancustomize, foremansettings]

- import_tasks: foreman-custom-network.yml
  tags: [foreman, foremancustomize, foremannetwork]

- import_tasks: foreman-custom-os.yml
  tags: [foreman, foremancustomize, foremanos]

- import_tasks: foreman-custom-groups.yml
  tags: [foreman, foremancustomize, foremangroups]

- import_tasks: foreman-custom-templates.yml
  tags: [foreman, foremancustomize, foremantemplates]

- import_tasks: apt-cache.yml
  tags: [foreman, foremanaptcache]
