---
- name: restart foreman-proxy
  set_fact:
    foreman_proxy_require_restart: True
#  service:
#    name: foreman-proxy
#    state: restarted
  listen: "restart_netboot_services"

- name: restart foreman
  set_fact:
    foreman_require_restart: True
#  service:
#    name: foreman
#    state: restarted
  listen: "restart_netboot_services"

- name: reload nginx config
  service:
    name: nginx
    state: reloaded

- name: capture_foreman_version
  command: foreman version
  register: foreman_version_results
  notify: set_foreman_version

- name: set_foreman_version
  set_fact:
    foreman_version: "{{ foreman_version_results.stdout }}"
  notify: display_foreman_version

- name: display_foreman_version
  debug:
    msg: "Foreman Installed Version is: {{ foreman_version }}"

- name: set foreman admin password
  command: "foreman-rake permissions:reset username={{ foreman_admin_user }} password={{ foreman_admin_password }}"
  when: foreman_pw_updated is changed or foreman_perform_rake_tasks
  no_log: True

- name: rebuild pxe default configs
  command: hammer template build-pxe-default
  notify: restart foreman-proxy

- name: restart apt-cacher-ng
  service:
    name: apt-cacher-ng
    state: restarted
