---
- name: restart foreman-proxy
  service:
    name: foreman-proxy
    state: restarted

- name: restart foreman
  service:
    name: foreman
    state: restarted

- name: capture_foreman_version
  command: foreman version
  register: foreman_version_results
  notify: set_foreman_version

- name: set_foreman_version
  set_fact:
    foreman_version: "{{ foreman_version_results.stdout }}"
  notify: display_foreman_version

- name: display_foreman_version
  debug:
    msg: "Foreman Installed Version is: {{ foreman_version }}"

- name: set foreman admin password
  command: "foreman-rake permissions:reset username={{ foreman_admin_user }} password={{ foreman_admin_password }}"
  when: foreman_pw_updated is changed or foreman_perform_rake_tasks
  no_log: True

- name: rebuild pxe default configs
  command: hammer template build-pxe-default
  notify: restart foreman-proxy