---
- name: restart foreman-proxy
  set_fact:
    foreman_proxy_require_restart: True
  listen: "restart_netboot_services"

- name: restart foreman
  set_fact:
    foreman_require_restart: True
  listen: "restart_netboot_services"

- name: reload nginx config
  service:
    name: nginx
    state: reloaded

- name: foreman_installed
  set_fact:
    foreman_pkgs_updated: True

- name: foreman_proxy_installed
  set_fact:
    foreman_proxy_pkgs_updated: True

- name: set foreman admin password
  command: "foreman-rake permissions:reset username={{ foreman_admin_user }} password={{ foreman_admin_password }}"
  when: foreman_pw_updated is changed or foreman_perform_rake_tasks
  no_log: True

- name: rebuild pxe default configs
  command: hammer template build-pxe-default
  notify: restart foreman-proxy

- name: restart apt-cacher-ng
  service:
    name: apt-cacher-ng
    state: restarted
